//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DummyDataGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DummyDataGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE DATABASE  IF NOT EXISTS `test_al_b2_d8` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION=&apos;N&apos; */;
        ///USE `test_al_b2_d8`;
        ///-- MySQL dump 10.13  Distrib 8.0.16, for Win64 (x86_64)
        ///--
        ///-- Host: localhost    Database: scm_test_dummy_generated_v2
        ///-- ------------------------------------------------------
        ///-- Server version	8.0.16
        ///
        ////*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
        ////*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESUL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mysql_generate_schema {
            get {
                return ResourceManager.GetString("mysql_generate_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE DATABASE  IF NOT EXISTS `test_ct_b2_d8` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION=&apos;N&apos; */;
        ///USE `test_ct_b2_d8`;
        ///-- MySQL dump 10.13  Distrib 8.0.16, for Win64 (x86_64)
        ///--
        ///-- Host: localhost    Database: scm_test_dummy_generated_v2
        ///-- ------------------------------------------------------
        ///-- Server version	8.0.16
        ///
        ////*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
        ////*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESUL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mysql_generate_schema_ct {
            get {
                return ResourceManager.GetString("mysql_generate_schema_ct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS 
        ///   (
        ///     SELECT name FROM master.dbo.sysdatabases 
        ///     WHERE name = N&apos;scm_b2_d2&apos;
        ///    )
        ///CREATE DATABASE [scm_b2_d2]
        ///GO
        ///
        ///USE [scm_b2_d2]
        ////****** Object:  Table [dbo].[activity]    Script Date: 27-6-2019 13:58:54 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [dbo].[activity](
        ///	[id] [int] IDENTITY(1,1) NOT NULL,
        ///	[GUID] [uniqueidentifier] NULL,
        ///	[name] [varchar](256) NULL,
        ///	[description] [varchar](max) NULL,
        ///	[created] [datetime] NULL,
        ///	[last_updated] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tsql_generate_schema {
            get {
                return ResourceManager.GetString("tsql_generate_schema", resourceCulture);
            }
        }
    }
}
